### PR TITLE
I194 husky setup

### LINKED ISSUE #194: Add pre-merge/pre-commit hooks with Husky in Firebase
Run linting and testing hooks before committing and merging.

*To do:*
- Add eslint to the project with plugins eslint-plugin-react & eslint-plugin-react-hooks. Check out the linting-setup branch of newslabs-cupid for config.
- Add husky
- As the project is totally unlinted suggest only running the linter on changed files. Set up Husky to do something like this: https://gist.github.com/seeliang/0f0de424d1cdc4541c338f4ee93b7e6a

### PR DESCRIPTION
**Pull request by aniablaziak**
**Is your Pull Request request related to another [issue](https://github.com/bbc/react-transcript-editor/issues) in this repository ?**      
Resolves #194 

**Describe what the PR does**    

- Sets up Husky
- Adds pre-commit and pre-merge hooks that will lint all staged files

TO DO: 
- test setup is currently broken and needs another ticket for fixing the issues and adding `npm test` to the hooks #215 

**State whether the PR is ready for review or whether it needs extra work**    

✔️ Ready
To set up Husky hooks run `npm i` 

**Additional context**    

- Uses previously exisiting eslint rules defined in `.eslintrc`
- To test locally change a `.js` file so that it breaks some of the eslint rules, add to staged and run `npm run pre-commit`, the linter should fix all errors

### CODE REVIEW

**Comment by sarahrainbow** [comment]
Looks great! Is this mean to just work in the `src` directory? Noticed that the linting was working in the `functions` directory and wondered whether that was expected behaviour?

**Review by tamsingreen — APPROVED** [review]
WFM! Thanks Anna.

**Review by sarahrainbow — APPROVED** [review]
👍 👍

**Comment by aniablaziak** [comment]
thanks! 🙂

**Pull request merged**
