### PR TITLE
Make Card URL an empty string, in case nothing has been set yet.

### LINKED ISSUE #62: Paper Edit interface goes white when creating a new Paper Edit
**Describe the bug**
Paper Edit interface goes white when creating a new Paper Edit. We need to refresh the page once to re-render the new paper edit. `location` is undefined, indicating that there might be some issue with the data we retrieve.

**To Reproduce**
1. Go to Paper Edit
2. Click on a button to create a new Paper Edit

**Expected behavior**
WE expect to see the page refresh as normal with the new paper edit.

**Screenshots**
Imagine a white screen...

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by emettely**
**Is your Pull Request request related to another [issue](https://github.com/bbc/react-transcript-editor/issues) in this repository ?**      
Fixes #62 

It's a tiny PR :)

**Describe what the PR does**    

**State whether the PR is ready for review or whether it needs extra work**    
Ready

**Additional context**

### CODE REVIEW

**Comment by bennuttall** [comment]
@allishultes did you have an issue with this branch?

**Comment by allishultes** [comment]
This fixed the issue in the list view of the paper edits, but when opening the newly created project we got errors about attempting to iterate over an undefined variable. Ben and I added a fix to `addWordsToSpeakersParagraphs` so that a newly created paper edit renders properly after being created.

**Comment by bennuttall** [comment]
@emettely happy with this but you might want to double check out recent commits 👍

**Comment by emettely** [comment]
Having a look at the above error - it was because the data we're getting in `makeListOfUniqueSpeakers` is wrong to begin with. We are passing in a document field called `transcript` which is the original response from the STT service. This has been since updated to `payload`. I'll double check, but also forEach, map functions shouldn't iterate over an empty array.

**Pull request merged**
