### PR TITLE
refactor(modals): #92 Update modal props

### PR DESCRIPTION
**Pull request by allishultes**
**Is your Pull Request request related to another [issue](https://github.com/bbc/react-transcript-editor/issues) in this repository ?**      

[Storybook i92](https://github.com/bbc/digital-paper-edit-storybook/issues/92)
[Storybook PR95](https://github.com/bbc/digital-paper-edit-storybook/pull/95)

**Describe what the PR does**    

- [x] Updates modal titles for programme scripts and changes ItemForm prop

**State whether the PR is ready for review or whether it needs extra work**    

WIP

**Additional context**    

Please see the Storybook PR linked above for testing instructions

### CODE REVIEW

**Review by aniablaziak — APPROVED** [review]
👍

**Comment by sarahrainbow** [comment]
getting this error when I `npm start` firebase after linking… 
Screenshot 2021-05-13 at 12 14 40

**Comment by allishultes** [comment]
> getting this error when I `npm start` firebase after linking… 

I think this is an npm link issue. I'm running with node v12 and have seen this issue when I've been using lower versions and/or creating a link without a package.dist.json, etc. Lmk if you want to do more pairing to hopefully get it working!

**Comment by allishultes** [comment]
Compared to live, the test version of the site, plus this branch, don't seem to allow users to upload a second media file when one is in the process of being uploaded. I reckon this might have to do with the new duration field (but maybe not)? Plus the jumping of the sort order is still very annoying. May raise new tickets but not sure they'll make it into this sprint backlog.

**Review by sarahrainbow — APPROVED** [review]
I heartily endorse this PR

**Pull request merged**
